const mongoose = require('mongoose');

const chatbotSchema = new mongoose.Schema({
    // Welcome message
    welcomeMessage: {
        type: String,
        default: "Hi! I'm VortexBot ML. How can I help you today?"
    },

    // Custom FAQ responses (admin-defined)
    customFAQs: [{
        question: { type: String, required: true },
        answer: { type: String, required: true },
        keywords: [{ type: String }], // Keywords to match
        category: { 
            type: String, 
            enum: ['events', 'club', 'website', 'general', 'registration', 'payment'],
            default: 'general'
        },
        enabled: { type: Boolean, default: true },
        usageCount: { type: Number, default: 0 }, // Track how often this FAQ is used
        lastUsed: { type: Date },
        // ML Enhancement: Track response quality
        qualityScore: { type: Number, default: 0 }, // Average user rating
        totalRatings: { type: Number, default: 0 },
        positiveRatings: { type: Number, default: 0 },
        negativeRatings: { type: Number, default: 0 },
        // Alternative answers learned from user feedback
        alternativeAnswers: [{
            answer: { type: String },
            score: { type: Number, default: 0 },
            usageCount: { type: Number, default: 0 },
            addedAt: { type: Date, default: Date.now }
        }]
    }],

    // ML Learning: User interactions that weren't matched
    learnedInteractions: [{
        userQuery: { type: String, required: true },
        timestamp: { type: Date, default: Date.now },
        frequency: { type: Number, default: 1 }, // How many times this query was asked
        suggestedAnswer: { type: String }, // Admin can provide answer
        approved: { type: Boolean, default: false }, // Admin approval
        category: { type: String },
        relatedQueries: [{ type: String }], // Similar queries
        // ML Enhancement: User feedback on suggested answers
        userFeedback: [{
            wasHelpful: { type: Boolean },
            comment: { type: String },
            timestamp: { type: Date, default: Date.now }
        }],
        // Auto-generated answer attempts
        autoGeneratedAnswers: [{
            answer: { type: String },
            confidence: { type: Number },
            source: { type: String }, // 'similar_faq', 'context', 'pattern'
            timestamp: { type: Date, default: Date.now }
        }]
    }],

    // ML Training Data: Successful interactions with feedback
    trainingData: [{
        query: { type: String },
        response: { type: String },
        wasHelpful: { type: Boolean },
        userRating: { type: Number, min: 1, max: 5 }, // 1-5 star rating
        userComment: { type: String },
        responseTime: { type: Number }, // ms
        timestamp: { type: Date, default: Date.now },
        // Context information
        context: {
            previousQuery: { type: String },
            sessionQueries: [{ type: String }],
            userType: { type: String } // 'new', 'returning'
        }
    }],

    // ML Enhancement: Pattern recognition
    queryPatterns: [{
        pattern: { type: String }, // Common query pattern
        category: { type: String },
        frequency: { type: Number, default: 1 },
        bestResponse: { type: String },
        confidence: { type: Number, default: 0 },
        lastUpdated: { type: Date, default: Date.now }
    }],

    // Quick reply suggestions
    quickReplies: [{
        text: { type: String },
        category: { type: String }
    }],

    // Chatbot settings
    settings: {
        enabled: { type: Boolean, default: true },
        responseDelay: { type: Number, default: 800 }, // ms
        showSuggestions: { type: Boolean, default: true },
        maxSuggestions: { type: Number, default: 3 },
        fallbackMessage: {
            type: String,
            default: "I'm learning from your question! Our team will review it soon. Meanwhile, would you like to contact us directly?"
        },
        mlEnabled: { type: Boolean, default: true }, // Enable ML learning
        autoLearnThreshold: { type: Number, default: 3 }, // Auto-create FAQ after N similar queries
        similarityThreshold: { type: Number, default: 0.7 }, // Similarity score for matching
        // ML Enhancement settings
        enableFeedback: { type: Boolean, default: true }, // Ask for user feedback
        enableAutoImprovement: { type: Boolean, default: true }, // Auto-improve responses
        minConfidenceScore: { type: Number, default: 0.6 }, // Minimum confidence to use learned response
        feedbackThreshold: { type: Number, default: 5 } // Min feedback count before auto-improvement
    },

    // Analytics
    analytics: {
        totalQueries: { type: Number, default: 0 },
        resolvedQueries: { type: Number, default: 0 },
        unresolvedQueries: { type: Number, default: 0 },
        learnedQueries: { type: Number, default: 0 },
        averageResponseQuality: { type: Number, default: 0 },
        totalFeedback: { type: Number, default: 0 },
        positiveFeedback: { type: Number, default: 0 },
        negativeFeedback: { type: Number, default: 0 },
        lastUpdated: { type: Date, default: Date.now }
    },

    updatedAt: { type: Date, default: Date.now }
});

// Update timestamp on save
chatbotSchema.pre('save', function(next) {
    this.updatedAt = Date.now();
    this.analytics.lastUpdated = Date.now();
    next();
});

module.exports = mongoose.model('Chatbot', chatbotSchema);
